name: Build and Push Docker Images

on:
  push:
    branches: release
  pull_request:
      paths:
        - docker-compose.yml
        - services
  workflow_dispatch:
    inputs:
      auto11:
        description: 'Build auto11 profile'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      comfy:
        description: 'Build comfy profile'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      download:
        description: 'Build download profile (always required)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
      dockerhub:
        description: 'Upload to Docker Hub'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      ghcr:
        description: 'Upload to GitHub Container Registry'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [auto11, comfy, download]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: inputs.dockerhub == 'true'
        uses: docker/login-action@v2
        with:
          username: leapingcroc
          password: ${{ secrets.DOCKERHUB_PSS }}

      - name: Log in to GitHub Container Registry
        if: inputs.ghcr == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker compose --progress plain --profile ${{ matrix.profile }} build 

      - name: Tag and Push Docker Image to Docker Hub
        if: inputs.dockerhub == 'true' && ((matrix.profile == 'auto11' && inputs.auto11 == 'true') || (matrix.profile == 'comfy' && inputs.comfy == 'true') || (matrix.profile == 'download'))
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF##*/}"
          else
            VERSION="${GITHUB_SHA}"
          fi
          IMAGE_NAME="leapingcroc/stable-diffusion-webui-docker"
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${{ matrix.profile }}_latest
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${{ matrix.profile }}_${VERSION}
          echo ${IMAGE_NAME}
          docker push ${IMAGE_NAME}:${{ matrix.profile }}_latest
          docker push ${IMAGE_NAME}:${{ matrix.profile }}_${VERSION}

      - name: Tag and Push Docker Image to GitHub Container Registry
        if: inputs.ghcr == 'true' && ((matrix.profile == 'auto11' && inputs.auto11 == 'true') || (matrix.profile == 'comfy' && inputs.comfy == 'true') || (matrix.profile == 'download'))
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF##*/}"
          else
            VERSION="${GITHUB_SHA}"
          fi
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/your-image:${{ matrix.profile }}"
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:latest
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${VERSION}
          docker push ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${VERSION}
